<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZendSkeletonModule\Module'                        => __DIR__ . '/Module.php',
    'ZendSkeletonModule\Controller\SkeletonController' => __DIR__ . '/src/ZendSkeletonModule/Controller/SkeletonController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
    'SevenWays\Db\Sql\Ddl\Column\Integer'              => __DIR__ . '/src/Core/SevenWays/Db/Sql/Ddl/Column/Integer.php',
);